message: "Hello, World Sai Ram!"
labels:
  env: prod
spec:
  destination:
    server: https://kubernetes.default.svc
  apps:
    ecsdemoFrontend:
      repoURL: git@github.com:aws-containers/ecsdemo-frontend.git
      targetRevision: main
      path: kubernetes/helm/ecsdemo-frontend
    ecsdemoNodejs:
      repoURL: git@github.com:aws-containers/ecsdemo-nodejs.git
      targetRevision: main
      path: kubernetes/helm/ecsdemo-nodejs
    ecsdemoCrystal:
      repoURL: git@github.com:aws-containers/ecsdemo-crystal.git
      targetRevision: main
      path: kubernetes/helm/ecsdemo-crystal
