apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: frontend
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: {{ .Values.spec.apps.ecsdemoFrontend.repoURL }}
    targetRevision: {{ .Values.spec.apps.ecsdemoFrontend.targetRevision }}
    path: {{ .Values.spec.apps.ecsdemoFrontend.path }}
    
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
